PlantApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('plant.urls', namespace='plant')),
    path('superadmin/', include('admin.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin/urls.py
from django.urls.conf import path

from . import views

app_name = 'admin'
urlpatterns = [
    path('', views.index, name="index"),
    # URLS Plant MODEL
    path('plants/', views.plants, name="plants"),
    path('plants/create', views.plant_create, name="plants.create"),
    path('plants/edit/<int:plant_id>', views.plant_edit, name="plants.edit"),
    path('plants/delete/<int:plant_id>', views.plant_delete, name="plants.delete"),
    # URLS Category MODEL
    path('categories/', views.categories, name="categories"),
    path('categories/create', views.categories_create, name="categories.create"),
    path('categories/edit/<int:category_id>', views.categories_edit, name="categories.edit"),
    path('categories/delete/<int:category_id>', views.categories_delete, name="categories.delete")
]

plant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import path
from . import views

app_name = 'plant'
urlpatterns = [
    path('', views.home.index, name="index"),
    path('register/', views.auth.register, name="auth.register"),
    path('login/', views.auth.login, name="auth.login"),
    path('logout/', views.auth.logout, name="auth.logout"),

    path('plants/', views.plant.index, name="plants.index"),
    path('plants/<str:plant_slug>', views.plant.detail, name="plants.detail"),
    path('categories/', views.category.categories, name="categories"),
    path('categories/<str:category_slug>', views.category.category_detail, name="category.detail"),
    path('favorite_plant/<str:username>', views.favorite_plant.index, name="favorite_plant.index"),
    path('favorite_plant/<str:username>/add/<str:plant_slug>', views.favorite_plant.add, name="favorite_plant.add"),
    path('favorite_plant/<str:username>/delete/<str:plant_slug>', views.favorite_plant.delete, name="favorite_plant.delete")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

plant/models/category.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=60)
    slug = models.CharField(max_length=60)
    description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.title

plant/models/favorite_plant.py
from django.db import models

from plant.models.plant import Plant


class FavoritePlant(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

plant/models/image_plant.py
from django.db import models


class ImagePlant(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    @property
    def get_image(self):
        return '/plant/media/' + self.image.name

    def __str__(self):
        return self.title

plant/models/plant.py
import os

from django.db import models

from plant.models.category import Category
from plant.models.image_plant import ImagePlant


class Plant(models.Model):
    title = models.CharField(max_length=60)
    slug = models.CharField(max_length=60)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    shade = models.CharField(max_length=50, null=True)
    moisture = models.CharField(max_length=50, null=True)
    wind = models.CharField(max_length=50, null=True)
    soil = models.CharField(max_length=50, null=True)
    growth_rate = models.CharField(max_length=50, null=True)

    image = models.OneToOneField(ImagePlant, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.title

plant/models/user.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager

from plant.models.favorite_plant import FavoritePlant


class UserManager(BaseUserManager):
    def create_user(self, username: str, password: str = None):
        if not username:
            raise ValueError('Users must have and a username')

        user = self.model(email=self.normalize_email('vincentcapek@gmail.com'))
        user.username = username
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username: str, password: str = None):
        user = self.create_user(
            username=username,
            password=password
        )
        user.admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=255, unique=True)
    email = models.CharField(max_length=255, unique=True, default="SOME EMAIL")
    password = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    admin = models.BooleanField(default=False)  # a superuser
    favorite_plants = models.ManyToManyField(FavoritePlant)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

    @property
    def is_admin(self):
        return self.admin

admin/views/plant.py
import os

from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.text import slugify

from plant.forms import PlantForm
from plant.models import Plant, ImagePlant


def plants(request):
    plants = Plant.objects.all()
    return render(request, 'admin/plants/index.html', {'plants': plants})


def plant_create(request):
    errors = None

    if request.method == 'POST':
        form = PlantForm(request.POST, request.FILES)
        # Check the form is valid
        if form.is_valid():
            title = form.cleaned_data['title']
            slug = slugify(title)
            description = form.cleaned_data['description']
            category = form.cleaned_data['category']
            # Other fields for the filter
            shade = form.cleaned_data['shade']
            moisture = form.cleaned_data['moisture']
            wind = form.cleaned_data['wind']
            soil = form.cleaned_data['soil']
            growth_rate = form.cleaned_data['growth_rate']

            image = getImagePlant(form.cleaned_data['image'])
            # Save plant model
            Plant.objects.create(title=title, slug=slug, description=description, category=category, image=image,
                                 shade=shade, moisture=moisture, wind=wind, soil=soil, growth_rate=growth_rate)
            # Redirect with success message
            messages.success(request, 'Vous avez crée une plante avec succès !')
            return HttpResponseRedirect(reverse('admin:plants'))
        else:
            errors = form.errors
    else:
        form = PlantForm()
    return render(request, 'admin/plants/create.html', {'form': form, 'errors': errors})


def plant_edit(request, plant_id: int):
    plant = get_object_or_404(Plant, pk=plant_id)
    errors = None
    if request.method == 'POST':
        form = PlantForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            slug = slugify(title)
            description = form.cleaned_data['description']
            category = form.cleaned_data['category']
            # Other fields for the filter
            shade = form.cleaned_data['shade']
            moisture = form.cleaned_data['moisture']
            wind = form.cleaned_data['wind']
            soil = form.cleaned_data['soil']
            growth_rate = form.cleaned_data['growth_rate']

            if form.cleaned_data['image'] is not None:
                image = getImagePlant(form.cleaned_data['image'])
            else:
                image = plant.image
            # Save plant model
            plant.title = title
            plant.slug = slug
            plant.description = description
            plant.category = category
            plant.shade = shade
            plant.moisture = moisture
            plant.wind = wind
            plant.soil = soil
            plant.growth_rate = growth_rate
            plant.image = image
            plant.save()
            # Redirect with success message
            messages.success(request, 'Vous avez edité une plante avec succès !')
            return HttpResponseRedirect(reverse('admin:plants'))
        else:
            errors = form.errors
    else:
        form = PlantForm(instance=plant)

    return render(request, 'admin/plants/edit.html', {'form': form, 'errors': errors})


def plant_delete(request, plant_id: int):
    plant = Plant.objects.filter(pk=plant_id)
    if not plant.exists():
        messages.error(request, 'Vous ne pouvez pas supprimer une plant qui n\'éxiste pas')
    else:
        plant_model = plant.first()
        if os.path.isfile(plant_model.image.image.path):
            os.remove(plant_model.image.image.path)
            plant_model.image.delete()
        plant.delete()
        messages.error(request, 'Vous avez supprimé cette plant avec success')
    return HttpResponseRedirect(reverse('admin:plants'))


def getImagePlant(image) -> ImagePlant:
    fs = FileSystemStorage()
    filename = fs.save(image.name, image)
    # Create new image plant model
    return ImagePlant.objects.create(title=image.name, image=filename)

plant/views/category.py
from django.shortcuts import render, get_object_or_404

from plant.models import Category, Plant
from plant.views.utils import Paginate


def categories(request):
    categories = Category.objects.all()
    return render(request, 'plant/category/index.html', {'categories': categories})


def category_detail(request, category_slug: str):
    category = get_object_or_404(Category, slug=category_slug)
    # Get all plants with the paginator
    plants = Plant.objects.filter(category=category).all()
    pagePlant = Paginate.getPaginate(request, plants)
    return render(request, 'plant/category/detail.html', {'category': category, 'pagePlant': pagePlant})

plant/views/favorite_plant.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from plant.models import FavoritePlant, Plant
from plant.models.user import CustomUser


@login_required
def index(request, username: str):
    print(CustomUser.objects.all())
    user = get_object_or_404(CustomUser, username=username)
    if request.user.username != user.username:
        return HttpResponseRedirect(reverse('plant:index'))

    plants_favorite = user.favorite_plants.all()
    return render(request, 'plant/favorite_plant/index.html', {'plants_favorite': plants_favorite})


@login_required
def add(request, username: str, plant_slug: str):
    user = get_object_or_404(CustomUser, username=username)
    plant = get_object_or_404(Plant, slug=plant_slug)
    if request.user.username != user.username:
        return HttpResponseRedirect(reverse('plant:index'))

    # Add the plant current in the favorite plant model to user authenticated
    favorite_plant = FavoritePlant.objects.filter(plant=plant)
    if not favorite_plant:
        favorite_plant = FavoritePlant.objects.create(plant=plant)
        user.favorite_plants.add(favorite_plant)
    else:
        messages.error(request, 'Vous avez déjà ajouté cette plante dans vos favoris !')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete(request, username: str, plant_slug: str):
    user = get_object_or_404(CustomUser, username=username)
    plant = get_object_or_404(Plant, slug=plant_slug)
    if request.user.username != user.username:
        return HttpResponseRedirect(reverse('plant:index'))

    # Delete the plant current in the favorite plant model to user authenticated
    favorite_plant = FavoritePlant.objects.filter(plant=plant)
    if favorite_plant.exists():
        favorite_plant.delete()
    else:
        messages.error(request, 'Vous ne pouvez pas supprimier une plante qui n\'est pas dans vos favoris !')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

plant/views/home.py
from django.shortcuts import render

from plant.models import Plant


def index(request):
    plants = Plant.objects.order_by('id')[:3]
    return render(request, 'plant/index.html', {'plants': plants})

plant/views/plant.py
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from plant.forms import PlantFilterForm
from plant.models import Category, Plant
from plant.views.utils import Paginate


def index(request):
    pagePlant = None

    # Request
    params = list(request.GET.items())
    if request.method == 'GET' and len(params) != 0 and request.GET.get('reset_filter') is None:
        form = PlantFilterForm(request.GET)

        # Check exist category model in our BDD
        searchCategoryField = request.GET.get('search_category')
        if searchCategoryField is not None and len(searchCategoryField) != 0:
            category = Category.objects.filter(id=searchCategoryField).first()
            if category is None:
                messages.success(request, 'Cette catégorie n\'est pas présente dans notre base de donnée !')
                return HttpResponseRedirect(reverse('plant:index'))

        if form.is_valid():
            # Fields to request
            args = {
                'title__contains': form.cleaned_data['search_plant'],
                'category': form.cleaned_data['search_category'],
                'shade': form.cleaned_data['search_shade'],
                'moisture': form.cleaned_data['search_moisture'],
                'wind': form.cleaned_data['search_wind'],
                'soil': form.cleaned_data['search_soil'],
                'growth_rate': form.cleaned_data['search_growth_rate']
            }
            for key in args.copy():
                item = args.get(key)
                if item is None:
                    args.pop(key)
                if type(item) == str and item is not None and len(item) == 0:
                    args.pop(key)

            # Query all plants
            if len(args) == 0:
                plants = []
            else:
                plants = Plant.objects.filter(**args).all()
            pagePlant = Paginate.getPaginate(request, plants)

    else:
        pagePlant = Paginate.getPaginate(request)
        form = PlantFilterForm()
    return render(request, 'plant/plant/index.html', {'pagePlant': pagePlant, 'form': form})


def detail(request, plant_slug: str):
    plant = get_object_or_404(Plant, slug=plant_slug)
    # Get plants by category
    plants_by_category = Plant.objects.filter(category=plant.category) \
        .exclude(id=plant.id) \
        .order_by('id') \
        .all()[:3]
    # Get plants related
    plants_related = related_plants(plant)
    return render(request, 'plant/plant/detail.html', {
        'plant': plant,
        'plants_by_category': plants_by_category,
        'plants_related': plants_related
    })

def related_plants(plant: Plant):
    description_current = plant.description

    plants_related = Plant.objects.filter(description__in=description_current).exclude(id=plant.id)
    plants_related = plants_related.annotate(some_description=Count('description'))
    return plants_related.order_by('id')[:3]

plant/templates/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- LINKS CSS -->
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'plant/css/app.css' %}">
</head>
<body>
{% include 'layout/header.html' %}
{% block content %}{% endblock %}
</body>
</html>

plant/templates/layout/header.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'plant:index' %}">PlantApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'plant:plants.index' %}">Plants</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'plant:categories' %}">Categories</a>
                    </li>
                </ul>
                <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'plant:favorite_plant.index' username=user.username %}"
                               class="nav-link text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi d-block mx-auto mb-1" viewBox="0 0 16 16">
                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"></path>
                                </svg>
                                Favorite
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'plant:auth.logout' %}"
                               class="nav-link text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi d-block mx-auto mb-1" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg>
                                Se déconnecter
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'plant:auth.login' %}"
                               class="nav-link text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi d-block mx-auto mb-1" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg>
                                Se connecter
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>